// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 65d8b47cbcca894c60e3f7179e279b3b)
declare namespace Cloudflare {
	interface Env {
		PETSITTER_DB: D1Database;
		PETSITTER_R2: R2Bucket;
		BETTER_AUTH_URL: string;
		GOOGLE_CLIENT_ID: string;
		GOOGLE_CLIENT_SECRET: string;
	}
}
interface Env extends Cloudflare.Env {}
