// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 65d8b47cbcca894c60e3f7179e279b3b)
declare namespace Cloudflare {
	interface Env {
		PETSITTER_DB: D1Database;
	}
}
interface Env extends Cloudflare.Env {}
