export const protectedRoutes = [
	{ path: "/api/auth/get-user", method: "GET" },
	{ path: "/profile", method: "PUT" },
	{ path: "/profile", method: "DELETE" },
	{ path: "/review", method: "POST" },
	{ path: "/review", method: "PUT" },
	{ path: "/review", method: "DELETE" },
	{ path: "/booking", method: "GET" },
	{ path: "/booking", method: "POST" },
	{ path: "/booking", method: "PUT" },
	{ path: "/booking", method: "DELETE" },
	{ path: "/chat", method: "GET" },
	{ path: "/chat", method: "POST" },
	{ path: "/chat", method: "PUT" },
	{ path: "/chat", method: "DELETE" },
	// { path: "/image", method: "POST" },
	// { path: "/image", method: "DELETE" },
	{ path: "/notification", method: "GET" },
	{ path: "/notification", method: "POST" },
	{ path: "/notification", method: "PUT" },
	{ path: "/notification", method: "DELETE" },
];
