export const protectedRoutes = [
	{ path: "/profile/createProfile", method: "POST" },
	{ path: "/profile/updateProfile", method: "PUT" },
	{ path: "/profile/deleteProfile", method: "DELETE" },
	{ path: "/review/createReview", method: "POST" },
	{ path: "/review/updateReview", method: "PUT" },
	{ path: "/review/deleteReview", method: "DELETE" },
	{ path: "/booking", method: "GET" },
	{ path: "/booking", method: "POST" },
	{ path: "/booking", method: "PUT" },
	{ path: "/booking", method: "DELETE" },
	{ path: "/chat", method: "GET" },
	{ path: "/chat", method: "POST" },
	{ path: "/chat", method: "PUT" },
	{ path: "/chat", method: "DELETE" },
	{ path: "/notification", method: "GET" },
	{ path: "/notification", method: "POST" },
	{ path: "/notification", method: "PUT" },
	{ path: "/notification", method: "DELETE" },
];
